/* This file index all components for easy importing */
export { default as About } from './About'
export { default as ErrorPage } from './ErrorPage'
export { default as Footer } from './Footer'
export { default as Header } from './Header'
export { default as Home } from './Home'
export { default as Logement } from './Logement'
export { default as App } from './App'
export { default as Banner } from './Banner'
export { default as Card } from './Card'
